export default {
  profile: {
    name: 'Allen Johnson',
    headline: 'Senior Software QA Automation Engineer & Tech Lead',
    location: 'Davao City, Philippines',
    status: 'Actively seeking new professional opportunities',
    coreSkills: [
      'Java',
      'Kotlin',
      'Swift',
      'Javascript',
      'UI Testing',
      'API Testing',
      'Integration Testing',
      'Unit Testing',
      'Test automation frameworks',
      'Mobile testing',
      'JUnit',
      'Selenium WebDriver',
      'Cucumber',
      'TestCafe',
      'Tape',
      'Postman',
      'cURL',
      'Charles Proxy',
      'Espresso',
      'XCUITest',
      'Test planning',
      'Test case design',
      'Requirements gathering',
      'Git',
      'Jenkins',
      'JIRA',
      'Confluence',
      'Pivotal Tracker',
      'Continuous Integration',
      'Android Studio',
      'Xcode',
      'IntelliJ',
      'VS Code',
      'Google Antigravity',
      'Gemini CLI Code Assist',
    ],
  },
  projects: [
    {
      id: 'proj_1',
      title: 'Visual Node-Based Automation Editor',
      summary: 'A spatial IDE for constructing automated test workflows via an infinite node-graph interface, featuring Bezier curve wiring and JSON serialization.',
      tags: ['DOMQL3', 'State Management', 'SVG Render'],
      bentoSize: 'large',
    },
    {
      id: 'proj_2',
      title: "Spatial 'Cyber-Deck' Lore Canvas",
      summary: 'A free-form glassmorphism whiteboard environment for mapping intricate relationships with active Z-index stacking.',
      tags: ['DOMQL3', 'Spatial Computing', 'UI/UX'],
      bentoSize: 'medium',
    },
    {
      id: 'proj_3',
      title: 'Multi-Track Timeline Sequencer',
      summary: 'A synchronized DAW-style timeline for sequencing high-density events with real-time DOM-to-time spatial manipulation.',
      tags: ['DOMQL3', 'Algorithms', 'Performance'],
      bentoSize: 'large',
    },
    {
      id: 'proj_4',
      title: 'Automated QA Test Run Dashboard',
      summary: 'A transactional execution environment for regression runs with high-density data grids and real-time metric aggregation.',
      tags: ['SQLite', 'API Middleware', 'Data Visualization'],
      bentoSize: 'medium',
    },
  ],
}
